include "personal/log4jball.yara"
include "personal/log4jimport.yara"
include "personal/log4jjavaclass.yara"
include "personal/log4jjavasrc.yara"
include "personal/log4jJndiLookup.yara"
include "CVE-2021-44228/rules/vulnerability/log4j/CVE-2021-44228.yar"
